### ISSUE TITLE
Error 0xb

### ISSUE THREAD

**Issue by NhanAZ** [Podrum/PodrumLegacy#141]
### Summary

Error 0xb : Could not connect to server

### Reproduction Steps

After entering the server I was dis
Once again, on the console it says:
[ERROR: 07:25] Terminating connectinon, due to malformed packet (0xb)

### Expected Results

I can connect to the server!

```
C:\Users\nhang\Desktop\Podrum-main>python3 run.py
[INFO: 07:23] Podrum is starting up...
[INFO: 07:23] Loading DevTools...
[INFO: 07:23] [ DevTools ] >> DevTools is on fire!!!
[INFO: 07:23] None
[SUCCESS: 07:23] Successfully loaded DevTools.
[SUCCESS: 07:23] Loaded world -> world
[SUCCESS: 07:23] Done in 0.031. Type help to view all available commands.
[INFO: 07:24] [ DevTools ] >> There is no plugins to load
[INFO: 07:24] None
[INFO: 07:24] 192.168.1.109:43045 connected.
[INFO: 07:24] NhanAZ logged in with uuid dcaec07f-6abc-3b29-8852-ccbce2c777dc.
[SUCCESS: 07:24] NhanAZ has all packs.
[INFO: 07:24] 192.168.1.109:43045 disconnected.
[INFO: 07:25] 192.168.1.109:43045 connected.
[INFO: 07:25] NhanAZ logged in with uuid dcaec07f-6abc-3b29-8852-ccbce2c777dc.
[SUCCESS: 07:25] NhanAZ has all packs.
**[ERROR: 07:25] Terminating connectinon, due to malformed packet (0xb)**
[INFO: 07:25] 192.168.1.109:43045 disconnected.
```

### Actual Results

I can't connect to the server!

### System Information

[INFO: 07:25] This server is running Podrum version 0.0.6 Platinum on API 0.0.1. This version is licensed under the GPL v2.0 license.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

After entering the server I get the message:
[ERROR: 07:25] Terminating connectinon, due to malformed packet (0xb)

**Comment by AnticcX** [comment]
Use minecraft 1.17.10 because we haven't updated to the latest protocol yet.

**Comment by NhanAZ** [comment]
> Use minecraft 1.17.10 because we haven't updated to the latest protocol yet.

Hope to update soon
