### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by NhanAZ** [Podrum/PodrumLegacy#148]
### Summary

Support more languages

### The Problem

Currently Podrum only supports English in the source code, which makes Podrum accessible to fewer people.

### The Ideal Solution

Support more languages (Not README)
This makes Podrum reach more people.

**Comment by Zekiah-A** [comment]
How would you change the language of the source code? :thinking:

**Comment by HunterAzar** [comment]
What are you mean by this?

Logger?
function names?
smth else?

**Comment by DRAGKILLS** [comment]
> What are you mean by this?
> 
> Logger? function names? smth else?

The messages

**Comment by NhanAZ** [comment]
> What are you mean by this?
> 
> Logger? function names? smth else?

All we can

**Comment by NhanAZ** [comment]
> How would you change the language of the sou

Write code.
I think it should be done now. It is essential.

**Comment by ZaZiDev** [comment]
The most people speak english very well so i think its not a big problem but we will add more languages in future

**Comment by NhanAZ** [comment]
> The most people speak english very well so i think its not a big problem but we will add more languages in future

I think adding the language is now necessary. Delaying it will make it difficult to add it in the future.
If you consider that most people speak English and this is not a big deal, why do big businesses always try to support more languages for users?

**Comment by Zekiah-A** [comment]
I would say that instead of updating Readme every 20 minutes, and adding languages, it would be WAY more useful if people actually contributed to the **_code_** and added new features / improved things with the server software

**Comment by ZaZiDev** [comment]
Podrum is in development the messages could change anytime so it makes no sense to now add more languages

**Comment by NhanAZ** [comment]
I'll close this with. Hope it can be updated in the future. Thanks to everyone commented.
