### ISSUE TITLE
Can't connect: Terminating connectinon, due to malformed packet (0xb)

### ISSUE THREAD

**Issue by socksprox** [Podrum/PodrumLegacy#155]
### Summary

Can't connect: Terminating connectinon, due to malformed packet (0xb)

### Reproduction Steps

Just try to connect, for me it did not worked

### Expected Results

I should connect to the server

### Actual Results

PS C:\Users\tamino\Downloads\TheProject Bedrock\Podrum> python run.py
//starting the server in Windows 11 with Terminal

[INFO: 15:57:39] Podrum is starting up...
[SUCCESS: 15:57:39] Loaded world -> world
[SUCCESS: 15:57:39] Done in 0.016. Type help to view all available commands.
[INFO: 15:57:44] 192.168.86.129:56496 connected.
[INFO: 15:57:45] ScanFee05 logged in with uuid 2ef27719-fda5-3471-abbe-e2893790db82.
[SUCCESS: 15:57:45] ScanFee05 has all packs.
[ERROR: 15:57:45] Terminating connectinon, due to malformed packet (0xb)
[INFO: 15:57:45] 192.168.86.129:56496 disconnected.

### System Information

This server is running Podrum version 0.0.6 Platinum on API 0.0.1. This version is licensed under the GPL v2.0 license.

**Python Version** 
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32

Windows 11 dev preview in 64 Bit
Amd Ryzen 5 3600
Nvidia Zotac RTX 2070 Super Mini

### Checklist

- [X] #156
- [X] I have shown the entire traceback, if possible.

### Additional Context

![grafik](https://user-images.githubusercontent.com/36358673/144447384-ef54f991-6eaa-47a8-bd1d-5abdd7ec991c.png)

**Comment by ZaZiDev** [comment]
Did you changed anything in the source code?

**Comment by socksprox** [comment]
> Did you changed anything in the source code?

I tried connecting with 1.18, maybe that was the problem.

**Comment by ZaZiDev** [comment]
okay the version 1.18 is not implemented yet thats why it gives an error
