### ISSUE TITLE
Why not use existing protocol libraries?

### ISSUE THREAD

**Issue by Heath123** [Podrum/PodrumLegacy#66]
For example [quarry](https://github.com/barneygale/quarry) or porting [ProtoDef](https://github.com/ProtoDef-io/ProtoDef) to Python to use the protocol in [minecraft-data](https://github.com/PrismarineJS/minecraft-data) (maybe using [python-minecraft-data](https://github.com/SpockBotMC/python-minecraft-data))?

**Comment by Heath123** [comment]
There's also https://github.com/SpockBotMC/SpockBot/blob/master/spockbot/mcp/proto.py

**Comment by MFDGaming** [comment]
@Heath123 no

**Comment by Heath123** [comment]
No what? I understand that writing your own could be better, but it was just a suggestion if you didn't know they exist (I didn't at first) and just saying "no" isn't really that helpful

**Comment by ZaZiDev** [comment]
We do it all ourselves

**Comment by MFDGaming** [comment]
> No what? I understand that writing your own could be better, but it was just a suggestion if you didn't know they exist (I didn't at first) and just saying "no" isn't really that helpful

@Heath123 I knew about those I just don’t want dependencies (Except toml and yaml) and I prefer making my own code
