### ISSUE TITLE
I Cannot join with Windows 10 edition :(

### ISSUE THREAD

**Issue by ZaZiDev** [Podrum/PodrumLegacy#75]
I Can`t join with windows 10 Edition :(

**Comment by kirillzhosul** [comment]
There is any error?

**Comment by ZaZiDev** [comment]
no

**Comment by ScarletRedMan** [comment]
Did you try run on your computer and join? If yes then system can block it. 
Just run PowerShell as Admin and run the following script
`CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"`

**Comment by ZaZiDev** [comment]
I can connect but cannot join

**Comment by HunterAzar** [comment]
> Did you try run on your computer and join? If yes then system can block it.
> Just run PowerShell as Admin and run the following script
> `CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"`

or type in powershell
`checknetisolation loopbackexempt -c`

**Comment by ZaZiDev** [comment]
i can connect! but when its connected the connection is away

**Comment by HunterAzar** [comment]
Oo i have similiar problem today
Maybe @MFDGaming done something that blocks you

**Comment by MFDGaming** [comment]
All is working rn

**Comment by MFDGaming** [comment]
For 1.16.220

**Comment by ZaZiDev** [comment]
okay i will close the issue :)
