### ISSUE TITLE
braking

### ISSUE THREAD

**Issue by plun1331** [Podrum/PodrumLegacy#76]
https://github.com/Podrum/Podrum/blob/276c6b0d6bd5b696b4d7dda5627cc69eef4c2448/podrum/player/bedrock_player.py#L111
https://github.com/Podrum/Podrum/blob/276c6b0d6bd5b696b4d7dda5627cc69eef4c2448/podrum/packet/mcbe/start_game_packet.py#L96

it's spelled 'breaking'

**Comment by ZaZiDev** [comment]
i will fix it :D
